### ISSUE TITLE
Allow customizing the `tokenField`

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication-client#38]
We should allow the client to use any fieldname in place of `accessToken`.  It's currently hard coded to `accessToken`, here: https://github.com/feathersjs/feathers-authentication-client/blob/master/src/passport.js#L235

I propose setting up a `tokenField` option to allow this.  This would solve https://github.com/feathersjs/feathers-authentication/issues/478

**Comment by ekryski** [comment]
Could you not just use a client side hook to translate to and from `accessToken` to the key name you want? I kind of wanted to reduce the number of config options because we had issues with so many in the last auth version. Also, when we bring in refresh token support I'd want to norm on `refreshToken`.

I'm not totally averse to having these customizable but I think it's less likely that people would need to do so.  feathersjs/feathers-authentication#478 seems to be a bit of an edge case.

**Comment by marshallswain** [comment]
Oh, good point @ekryski.

@prime-ralph, can you try this before you finish your PR?

**Comment by prime-ralph** [comment]
It just so happened that, while we may have these norms, there are existing endpoint implementations that deviate from those, and well, there are some of us who take the brunt of it. But yeah, it is an edge case lol.

Yeah, suddenly it clicked for me as well, the use of client side hooks. I hadn't thought of that. Thanks for the guidance! 😄

**Comment by ekryski** [comment]
Yeah, let us know if that works for you. If not, we can totally investigate further but in order to pursue the custom option we'll likely need the option server side as well and we'd need to try and toss some intelligent warnings/errors in the event that people set the value only on the server or the client.

Let us know how it goes...

**Comment by prime-ralph** [comment]
Here's how it ended up for me. https://github.com/feathersjs/feathers-authentication/issues/478#issuecomment-293169501

**Comment by marshallswain** [comment]
Thanks @prime-ralph.  I'm glad it worked.

I no longer feel like it's necessary to implement this as an option.  A hook offers infinite flexibility.  I'd prefer to steer folks to use hooks, since this works great.  I'm going to close this, but feel free to reopen @ekryski.

**Comment by ekryski** [comment]
Nope. I agree that hooks are a better option (they usually are once you remember you can use them on the client too).
